
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - 443:443
    depends_on:
      - php-wordpress
    networks:
      - internal
    volumes:
      - wp-files:/var/www/html

  php-wordpress:
    build:
      context: requirements/php-wordpress
      dockerfile: Dockerfile
    image: my_php
    ports:
      - 9000:9000
    expose:
      - 9000
    working_dir: /var/www/html
    depends_on:
       - maria-db
    networks:
      - internal
    volumes:
      - wp-files:/var/www/html
    env_file:
      - requirements/.env

  maria-db:
    build:
      context: requirements/maria-db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    networks:
      - internal
    env_file:
      - requirements/.env
    environment:
      - TEST=ICI
    volumes:
     - wp-db:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  wp-db:
    driver: local
    driver_opts:
      type: none
      device: /home/ccommiss/data/wp-db
      o: bind

  wp-files:
    driver: local
    driver_opts:
      type: none
      device: /home/ccommiss/data/wp-files
      o: bind
