
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - 80:80
    depends_on:
       - php-wordpress
    networks:
      - internal
    # links:
    #   - php-wordpress

  php-wordpress:
    build:
      context: ./php-wordpress
      dockerfile: Dockerfile
    image: my_php
    ports:
      - 9000:9000
    expose:
      - 9000
    working_dir: /var/www/html
    depends_on:
       - maria-db
    networks:
      - internal
    environment:
      WORDPRESS_DB_HOST: maria-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  maria-db:
    build:
      context: ./maria-db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

# networks permet de faire la co genre php:9000
networks:
  internal:
    driver: bridge