
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - 443:443
    depends_on:
       - php-wordpress
    networks:
      - internal
    volumes:
      - /home/ccommiss/data:/var/www/html
    # links:
    #   - php-wordpress

  php-wordpress:
    build:
      context: ./php-wordpress
      dockerfile: Dockerfile
    image: my_php
    ports:
      - 9000:9000
    expose:
      - 9000
    working_dir: /var/www/html
    depends_on:
       - maria-db
    networks:
      - internal
    volumes:
      - /home/ccommiss/data:/var/www/html

  maria-db:
    build:
      context: ./maria-db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    #volumes:
    #  - $PWD/data:/var/lib/mysql

# networks permet de faire la co genre php:9000
networks:
  internal:
    driver: bridge

volumes:
  wp-db:

  wp-files:
    name: wp-files
